FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# 1) copy only reqs first to leverage cache correctly
COPY requirements.txt .

# 2) install deps (no cache to avoid stale wheels)
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# 3) now copy the app
COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
